import { negatives } from '@upspawn/ads'

export const shared = negatives(
  'adobe',
  'advanced renamer',
  'alternative',
  'annotate',
  'backup',
  'bash',
  'bigpdf',
  'bulk rename utility',
  'certificate',
  'change file name',
  'combine',
  'combiner',
  'command line',
  'compress',
  'compressed zip',
  'conventions',
  'convert',
  'crack',
  'document management system',
  'download',
  'editor',
  'excel',
  'file naming conventions',
  'fill',
  'foxit',
  'free',
  'free online',
  'freeware',
  'google d o c s',
  'google doc',
  'google document',
  'google document editor',
  'google documents online',
  'google word',
  'guide',
  'hipdf',
  'how to',
  'how to create file name',
  'how to rename',
  'how to rename a file',
  'how to rename files',
  'how to rename folder',
  'how to rename photos',
  'ilovepdf',
  'learn',
  'lightpdf',
  'linux',
  'mac',
  'merge',
  'music',
  'note generator',
  'open source',
  'pdf candy',
  'pdf compressor',
  'pdf page remover',
  'pdf24',
  'pdfelement',
  'pdffiller',
  'pdffiller com',
  'pdnob',
  'permission',
  'photos',
  'power automate',
  'powerautomate',
  'powershell',
  'pricing',
  'printable list',
  'redact',
  'rename a document in excel',
  'rename file on word',
  'rename folder in windows',
  'rename photos on laptop',
  'renamebest',
  'resize',
  'rotate',
  'scanner',
  'sejda',
  'sign',
  'smallpdf',
  'space',
  'split',
  'storage',
  'summarize',
  'sync',
  'tenorshare',
  'terminal',
  'torrent',
  'tutorial',
  'upscale',
  'upscale file',
  'upscale file pdf',
  'upscale pdf',
  'video',
  'watermark',
  'what is',
  'windows 11',
  'windows file organizer',
  'word',
  'zusammenfassen',
  'zusammenfassung',
)
