// Imported from Google Ads on 2026-03-15
import { broad, daily, descriptions, exact, google, headlines, phrase, rsa, url } from '@upspawn/ads'

export default google.search('Search - Exact Match', {
  budget: daily(3),
  bidding: 'maximize-clicks',
  negatives: [...broad(
    'free',
    'job',
    'jobs',
    'gratis',
    'linux',
    'convert',
    'download',
    'guide',
    'excel',
    'tutorial',
    'freeware',
    'example',
    'kostenlos',
    'mac',
    'how to',
    'ocr',
    'crack',
    'training',
    'scanner',
    'hiring',
    'examples',
    'definition',
    'course',
    'powerpoint',
    'career',
    'resume',
    'free online',
    'sign',
    'document management system',
    'salary',
    'word',
    'fill',
    'adobe',
    'certificate',
    'exe',
    'learn',
    'open source',
    'watermark',
    'nuance',
    'android',
    'what is',
    'terminal',
    'cmd',
    'editor',
    'annotate',
    'hazel',
    'iphone',
    'combine',
    'upscale',
    'bash',
    'pdf editor',
    'command line',
    'margins',
    'merge',
    'remover',
    'file extension',
    'compress',
    'font size',
    'rotate',
    'ipad',
    'rearrange',
    'torrent',
    'redact',
    'bulk rename utility',
    'macbook',
    'windows 11',
    'better file rename',
    'foxit',
    'powershell',
    'zip folder',
    'chromebook',
    'github',
    'pdffiller',
    'fileservice',
    'tenorshare',
    'smallpdf',
    'remove pages',
    'advanced renamer',
    'note generator',
    'change file type',
    'ilovepdf',
    'sejda',
    'pdnob',
    'hipdf',
    'file juggler',
    'renamebest',
  ), ...phrase(
    'free',
    'resize',
    'online',
    'kostenlos',
    'conventions',
    'zusammenfassung',
    'combiner',
    'change file name',
    'summarize',
    'google word',
    'google doc',
    'pdf24',
    'pdffiller com',
    'pdfelement',
    'pdf page remover',
    'how to rename a file',
    'pdf compressor',
    'printable list',
    'zusammenfassen',
    'windows file organizer',
    'how to rename photos',
    'google document',
    'google document editor',
    'google documents online',
    'how to rename',
    'file naming conventions',
    'compressed zip',
    'pdf candy',
    'lightpdf',
    'power automate',
    'powerautomate',
    'how to rename files',
    'how to rename folder',
    'upscale pdf',
    'bigpdf',
    'rename folder in windows',
    'rename a document in excel',
    'rename file on word',
    'rename photos on laptop',
    'upscale file pdf',
    'how to create file name',
    'upscale file',
    'google d o c s',
  ), ...exact(
    'split pdf',
    'pdf split',
    'split pdf online',
    'pdf splitten online',
  )],
})
  .group('ai-file-renaming', {
    keywords: [...broad(
    'ai file renamer',
    'ai rename files',
    'ai renamer',
    'automatic file naming',
    'smart file renamer',
  )],
    ad: rsa(
      headlines(
        'AI Analyzes & Names Files',
        'AI File Renamer - Try Free',
        'AI Names Any File Type',
        'AI Renames Files by Content',
        'Automatic File Naming Tool',
        'Intelligent File Naming',
        'Let AI Organize Your Files',
        'No Setup - AI Handles It',
        'Rename PDF files automatically',
        'Smart File Renamer with AI',
        'Try Free - No Credit Card',
      ),
      descriptions(
        'AI reads your files and creates meaningful names. Any file type. Try free.',
        'AI-powered file naming for invoices, contracts, and photos. Done in seconds.',
        'Stop naming files manually. AI understands content and renames automatically.',
        'Upload files, get smart names in seconds. No rules or patterns to configure.',
      ),
      url('https://www.renamed.to/pdf-renamer'),
    ),
  })
  .group('bulk-file-renamer', {
    keywords: [...broad('batch rename files', 'bulk file changer'), ...exact('bulk rename files', 'rename files in bulk')],
    ad: rsa(
      headlines(
        'AI Reads Files, Names Them',
        'Batch Rename Files with AI',
        'Bulk File Renamer - Try Free',
        'Bulk Rename by File Content',
        'No Rules - AI Does It All',
        'Rename 1000 Files in Seconds',
        'Rename PDF files automatically',
        'Rename PDFs, Images & Docs',
        'Stop Renaming Files Manually',
        'Try Free - No Credit Card',
        'Upload Files, Get Names Back',
      ),
      descriptions(
        'No rules or regex needed. AI reads each file and creates meaningful names.',
        'Rename hundreds of files in seconds. Invoices, contracts, photos - all handled.',
        'Trusted by freelancers and small businesses. Works with any file type.',
        'Upload files in bulk, AI renames by content. PDFs, images, docs. Try free today.',
      ),
      url('https://www.renamed.to/pdf-renamer'),
    ),
  })
  .group('google-drive-renaming', {
    keywords: [...broad('bulk rename google drive', 'google drive file organizer', 'rename files in google drive')],
    ad: rsa(
      headlines(
        '50 Files Free Every Month',
        'AI Reads Content, Names Files',
        'AI Renames Your Drive Files',
        'Auto Bulk Rename PDFs',
        'Bulk Rename in Google Drive',
        'Connect Drive in One Click',
        'Free, no credit card',
        'From $9 for 1,000 Documents',
        'Google Drive File Organizer',
        'Made in Germany. GDPR Ready.',
        'No Rules. No Regex. Just AI.',
        'Rename Files in Google Drive',
      ),
      descriptions(
        'AI understands invoices, contracts, and receipts. Names them by vendor, date, and type.',
        'Connect Google Drive, select a folder. AI reads each file and renames it. 50 free/month.',
        'Stop renaming Scanner_001.pdf by hand. AI names files by content: invoices, contracts.',
        'Used by 70+ businesses. Works with PDFs, photos, scans. One-click Google Drive connection.',
      ),
      url('https://www.renamed.to/integrations/google-drive'),
    ),
  })
  .group('invoice-renaming', {
    keywords: [...exact('auto rename invoices', 'invoice renaming tool'), ...broad('auto rename invoices', 'automatically rename invoices', 'invoice renaming tool')],
    ad: rsa(
      headlines(
        '70+ SMBs Use It Daily',
        'AI Reads & Names Invoices',
        'Auto-Rename Invoices w/ AI',
        'By Vendor, Date, and Amount',
        'From $9 for 1,000 Documents',
        'Invoice Renamer - 50 Free',
        'Invoices Named in Seconds',
        'Made in Germany. GDPR Ready.',
        'No Rules. No Regex. Just AI.',
        'Stop Renaming by Hand',
      ),
      descriptions(
        'AI reads invoices, names them by vendor, date, and amount. 50 free/month, then $9/1,000.',
        'Upload Scanner_001.pdf, get Invoice-Acme-Jan2026.pdf back. No templates needed.',
        'Used by accountants, bookkeepers, and finance teams. 36,000+ files processed monthly.',
        'Works with scanned PDFs, photos of receipts, and digital invoices. Try 50 files free.',
      ),
      url('https://www.renamed.to/solutions/accountants'),
    ),
  })
  .group('pdf-renamer', {
    keywords: [...exact('auto rename pdf'), ...broad(
    'pdf rename',
    'pdf rename tool',
    'pdf renamer',
    'rename pdf file',
  )],
    ad: rsa(
      headlines(
        'AI PDF File Renamer',
        'AI Reads PDFs, Names Them',
        'Auto-Name Your PDF Files',
        'Bulk Rename PDF Files',
        'PDF Renamer - No Setup',
        'PDF Renamer - Try Free',
        'Rename Invoices by Vendor',
        'Rename PDF files automatically',
        'Rename PDFs by Content',
        'Rename Scanned PDFs Too',
        'Try Free - No Credit Card',
      ),
      descriptions(
        'AI reads PDFs and creates meaningful file names. Handles scanned docs too.',
        'Rename hundreds of PDFs in seconds. AI extracts dates, vendors, amounts.',
        'Stop renaming PDFs one by one. Upload a batch and let AI handle naming.',
        'Upload PDFs, AI renames by content. Invoices, contracts, reports. Try free.',
      ),
      url('https://www.renamed.to/pdf-renamer'),
    ),
  })
  .group('pdf-split-rename', {
    keywords: [...broad(
    'ai pdf splitter',
    'combine',
    'compress',
    'content split pdf',
    'convert',
    'cut pdf pages out',
    'demerge pdf',
    'divide pdf document',
    'divide pdf file',
    'divide pdf into multiple files',
    'document splitter',
    'edit',
    'fill',
    'intelligent document splitter',
    'join',
    'merge',
    'pdf document splitter',
    'pdf separate',
    'pdf separator',
    'pdf splitter',
    'pdf splitter and renamer',
    'pdf splitter tool',
    'pdf teilen',
    'pdf trennen',
    'rotate',
    'separate pdf pages',
    'sign',
    'split and rename pdf',
    'split pages',
    'split pdf into multiple files and rename',
    'unmerge pdf file',
    'watermark',
  ), ...exact(
    'automatically split and rename pdf',
    'divide pdf and rename',
    'split pdf and rename',
    'split pdf and rename based on content',
  )],
    ad: rsa(
      headlines(
        '100-Page PDF Split in 30s',
        '36K+ Files Processed Monthly',
        '50 Free Credits. No Card.',
        '97% Detection Accuracy',
        'AI PDF Splitter',
        'AI Splits & Names Each File',
        'How AI splitting works',
        'Invoices, Contracts, Scans',
        'Made in Germany. GDPR Ready',
        'Split + Rename in One Step',
        'Split PDF & Rename Files',
        'Stop Splitting PDFs Manually',
      ),
      descriptions(
        'AI reads content to find document boundaries. Split + rename in seconds.',
        'Only tool that splits AND renames PDFs in one step. 97% accuracy. Try free.',
        'Split invoice bundles and contract packages. AI names each file. Try free.',
        'Upload a multi-doc PDF. AI splits and renames each file by content. 50 free credits.',
      ),
      url('https://www.renamed.to/pdf-split'),
    ),
  })
