// Imported from Google Ads on 2026-03-15
import { broad, daily, descriptions, exact, google, headlines, phrase, rsa, url } from '@upspawn/ads'

export default google.search('Search - Google Drive', {
  budget: daily(4),
  bidding: 'maximize-clicks',
  negatives: [...broad(
    'storage',
    'free',
    'convert',
    'share',
    'download',
    'tutorial',
    'how to',
    'photos',
    'upload',
    'scanner',
    'space',
    'alternative',
    'free online',
    'permission',
    'certificate',
    'slides',
    'open source',
    'sheets',
    'split',
    'sharing',
    'pricing',
    'what is',
    'editor',
    'combine',
    'docs',
    'merge',
    'compress',
    'tenorshare',
    'folder rename',
    'note generator',
    'pdnob',
    'hipdf',
  ), ...phrase(
    'document management system',
    'resize',
    'upscale',
    'conventions',
    'zusammenfassung',
    'combiner',
    'change file name',
    'summarize',
    'google word',
    'google doc',
    'pdf24',
    'pdffiller',
    'pdffiller com',
    'pdfelement',
    'pdf page remover',
    'how to rename a file',
    'bulk rename utility',
    'pdf compressor',
    'printable list',
    'zusammenfassen',
    'windows file organizer',
    'how to rename photos',
    'google document',
    'google document editor',
    'google documents online',
    'how to rename',
    'file naming conventions',
    'compressed zip',
    'pdf candy',
    'lightpdf',
    'power automate',
    'powerautomate',
    'how to rename files',
    'how to rename folder',
    'upscale pdf',
    'bigpdf',
    'renamebest',
    'rename folder in windows',
    'rename a document in excel',
    'rename file on word',
    'rename photos on laptop',
    'upscale file pdf',
    'how to create file name',
    'upscale file',
    'google d o c s',
  )],
})
  .group('google-drive-intercept-en', {
    keywords: [...phrase('automate google drive', 'google drive for law firm'), ...broad(
    'automate google drive',
    'can gemini rename files in google drive',
    'google drive document organization',
    'google drive file management tool',
    'google drive for accounting',
    'google drive for construction',
    'google drive for law firm',
    'google drive naming convention',
    'google drive rename tool',
    'google workspace file management',
    'manage shared drive files',
  )],
    ad: rsa(
      headlines(
        '50 Free Renames Monthly',
        'AI Reads PDFs & Names Them',
        'Auto-Rename Files in Drive',
        'Bulk Rename Google Drive Files',
        'Connect Drive. AI Names Files.',
        'Custom Templates Per Folder',
        'Enforce Naming Conventions',
        'Free, no credit card',
        'No Manual Renaming Ever Again',
        'Scanned Docs Work Too',
        'What Gemini Can\'t Do — We Can',
      ),
      descriptions(
        'Enforce naming conventions across Drive. AI reads PDFs, renames them.',
        'Gemini can\'t rename Drive files. We can. Set rules, AI renames all.',
        'Invoices, contracts, receipts. Custom templates. 95% accuracy. Free.',
        'Stop renaming files manually. AI watches folders, names every PDF.',
      ),
      url('https://www.renamed.to/integrations/google-drive'),
    ),
  })
  .group('google-drive-rename-en', {
    keywords: [...broad(
    'ai google drive organizer',
    'automate google drive file naming',
    'bulk rename google drive',
    'clean up google drive',
    'google drive file naming rules',
    'google drive file organization',
    'google drive file renamer',
    'google drive folder structure',
    'organize google drive automatically',
    'organize google drive files',
    'rename files in google drive',
    'rename google drive pdfs',
  ), ...exact('automate google drive file naming', 'google drive bulk rename files', 'rename multiple files in google drive')],
    ad: rsa(
      headlines(
        '50 Free Documents Monthly',
        '95% Accuracy on Invoices',
        'AI Organizes Your Drive PDFs',
        'Connect Once, Rename Forever',
        'Connect in 60 Seconds',
        'Drive File Chaos? Fixed by AI',
        'Free, no credit card',
        'Made in Germany. GDPR Ready.',
        'Monitors Subfolders Too',
        'No Zapier. No Scripts. AI.',
        'PDFs Named in 60 Seconds',
        'Rename Google Drive Files — AI',
        'Set Rules Once — AI Does Rest',
      ),
      descriptions(
        'Auto-rename new files. Monitors subfolders. Custom templates. 50 free.',
        'Bookkeepers & accountants: organize Drive automatically. 95% accuracy.',
        'Connect Drive. AI reads invoices, receipts, contracts — renames by content.',
        'Stop renaming files manually. Connect once, AI watches folders. Done.',
      ),
      url('https://www.renamed.to/integrations/google-drive'),
    ),
  })
