// Imported from Google Ads on 2026-03-14
import { daily, descriptions, exact, google, headlines, phrase, rsa, url } from '@upspawn/ads'

export default google.search('Search - Dropbox', {
  budget: daily(0.5),
  bidding: { type: 'target-cpa', targetCpa: 0 },
  negatives: [...exact(
    'document management system',
    'resize',
    'upscale',
    'conventions',
    'zusammenfassung',
    'combiner',
    'change file name',
    'summarize',
    'google word',
    'google doc',
    'pdf24',
    'pdffiller',
    'pdffiller com',
    'pdfelement',
    'pdf page remover',
    'how to rename a file',
    'bulk rename utility',
    'pdf compressor',
    'printable list',
    'zusammenfassen',
    'windows file organizer',
    'how to rename photos',
    'google document',
    'google document editor',
    'google documents online',
    'how to rename',
    'file naming conventions',
    'compressed zip',
    'pdf candy',
    'lightpdf',
    'power automate',
    'powerautomate',
    'how to rename files',
    'how to rename folder',
    'upscale pdf',
    'bigpdf',
    'renamebest',
    'rename folder in windows',
    'rename a document in excel',
    'rename file on word',
    'rename photos on laptop',
    'upscale file pdf',
    'how to create file name',
    'upscale file',
    'google d o c s',
  ), ...exact(
    'storage',
    'video',
    'free',
    'convert',
    'download',
    'tutorial',
    'fax',
    'music',
    'paper',
    'how to',
    'photos',
    'scanner',
    'sync',
    'space',
    'alternative',
    'transfer',
    'free online',
    'backup',
    'sign',
    'install',
    'certificate',
    'open source',
    'split',
    'pricing',
    'what is',
    'editor',
    'signature',
    'combine',
    'merge',
    'app',
    'compress',
    'tenorshare',
    'note generator',
    'pdnob',
    'hipdf',
  )],
})
  .group('dropbox-automation-en', {
    keywords: [...phrase(
    'automate dropbox',
    'automate dropbox folder creation',
    'automate file organization in dropbox',
    'bulk rename dropbox',
    'clean up dropbox files',
    'dropbox automation tool',
    'dropbox file management tool',
    'dropbox file organization tool',
    'dropbox file organizer',
    'dropbox file renamer',
    'dropbox naming convention',
    'dropbox rename files automatically',
    'organize dropbox files automatically',
    'rename files in dropbox',
  )],
    ad: rsa(
      headlines(
        '50 Free Documents Monthly',
        '95% Accuracy on Documents',
        'AI Organizes Automatically',
        'AI Renames PDFs by Content',
        'Automate Dropbox File Naming',
        'Connect Dropbox in 3 Minutes',
        'Custom Naming Conventions',
        'Invoices Renamed in Seconds',
        'Made in Germany. GDPR Ready.',
        'No Zapier. No Scripts. AI.',
        'Set Rules Once — Runs Forever',
        'Tired of Messy Dropbox Files?',
      ),
      descriptions(
        'Connect Dropbox. AI reads PDFs — dates, amounts, names. No Zapier.',
        'Forget Zapier workflows. Connect Dropbox, set rules, AI handles it.',
        'Replaces manual renaming. 3-minute setup. 50 free docs. No card.',
        'Stop renaming PDFs by hand. AI reads invoices, names them. Done.',
      ),
      url('https://www.renamed.to/integrations/dropbox'),
    ),
  })
  .group('dropbox-industry-en', {
    keywords: [...phrase(
    'dropbox document management',
    'dropbox folder structure',
    'dropbox for accounting firms',
    'dropbox for bookkeepers',
    'dropbox for business file management',
    'dropbox for contractors',
    'dropbox for law firm',
    'organize dropbox for business',
  )],
    ad: rsa(
      headlines(
        'AI Reads & Names Your PDFs',
        'Auto-Name Client Documents',
        'Custom Templates per Client',
        'Dropbox Document Management',
        'Dropbox for Accountants — AI',
        'Invoices Renamed in Seconds',
        'Naming Conventions Enforced',
        'Save 10+ Hours per Week',
        'Try Free — No Credit Card',
        'Works with Scanned Docs',
      ),
      descriptions(
        '400+ teams use it. Set naming rules once, AI handles new files. Free.',
        'AI reads content, renames files. Invoices, receipts. 3-minute setup.',
        'Bookkeepers: stop renaming PDFs. AI names them — date, amount, vendor.',
        'Save 10+ hrs/week. Custom templates per client folder. 50 free docs.',
      ),
      url('https://www.renamed.to/integrations/dropbox'),
    ),
  })
