// Imported from Google Ads on 2026-03-15
import { broad, daily, descriptions, google, headlines, phrase, rsa, url } from '@upspawn/ads'

export default google.search('Search - OneDrive + SharePoint', {
  budget: daily(3),
  bidding: 'maximize-clicks',
  negatives: [...broad(
    'video',
    'free',
    'convert',
    'excel',
    'tutorial',
    'music',
    'how to',
    'photos',
    'recovery',
    'scanner',
    'sync',
    'space',
    'backup',
    'permission',
    'word',
    'certificate',
    'outlook',
    'learn',
    'split',
    'what is',
    'editor',
    'teams',
    'combine',
    'permissions',
    'merge',
    'compress',
    'personal vault',
    'tenorshare',
    'note generator',
    'pdnob',
    'hipdf',
    'power automate excel',
    'power automate email',
    'power automate teams',
    'power automate sharepoint list',
    'power automate approval',
  ), ...phrase(
    'document management system',
    'resize',
    'upscale',
    'conventions',
    'zusammenfassung',
    'combiner',
    'change file name',
    'summarize',
    'google word',
    'google doc',
    'pdf24',
    'pdffiller',
    'pdffiller com',
    'pdfelement',
    'pdf page remover',
    'how to rename a file',
    'bulk rename utility',
    'pdf compressor',
    'printable list',
    'zusammenfassen',
    'windows file organizer',
    'how to rename photos',
    'google document',
    'google document editor',
    'google documents online',
    'how to rename',
    'file naming conventions',
    'compressed zip',
    'pdf candy',
    'lightpdf',
    'powerautomate',
    'how to rename files',
    'how to rename folder',
    'upscale pdf',
    'bigpdf',
    'renamebest',
    'rename folder in windows',
    'rename a document in excel',
    'rename file on word',
    'rename photos on laptop',
    'upscale file pdf',
    'how to create file name',
    'upscale file',
    'google d o c s',
  )],
})
  .group('onedrive-rename-en', {
    keywords: [...broad(
    'bulk rename onedrive',
    'clean up onedrive',
    'onedrive document management',
    'onedrive file organization',
    'onedrive file organization tool',
    'onedrive file renamer',
    'onedrive folder structure',
    'onedrive for business file management',
    'organize onedrive files',
    'organize onedrive files automatically',
    'rename files in onedrive',
  ), ...phrase('onedrive file organization tool', 'onedrive rename multiple files', 'rename onedrive files')],
    ad: rsa(
      headlines(
        '50 Free Documents Monthly',
        '95% Accuracy on Invoices',
        'AI Reads Content & Names Files',
        'Auto-Rename PDFs & Scans',
        'Connect in 3 Minutes',
        'Custom Naming Templates',
        'Free, no credit card',
        'Made in Germany. GDPR Ready.',
        'OneDrive File Organizer — AI',
        'OneDrive Integration',
        'OneDrive Personal & Business',
        'Works with SharePoint Too',
      ),
      descriptions(
        'Connect OneDrive. AI reads PDFs, extracts dates and names, renames all.',
        'OneDrive Business + SharePoint. 3-minute setup. 50 free docs. No card.',
        'Save 10+ hrs/week. Custom templates. 95% accuracy on invoices.',
        'Stop renaming files manually. AI watches folders, names every new PDF.',
      ),
      url('https://www.renamed.to/integrations/onedrive'),
    ),
  })
  .group('power-automate-intercept-en', {
    keywords: [...broad(
    'automate file management microsoft',
    'automate file renaming onedrive',
    'microsoft 365 file organization',
    'power automate file naming',
    'power automate file organization',
    'power automate organize files',
    'power automate rename files',
    'power automate rename files based on content',
    'power automate rename pdf',
    'power automate rename pdf based on content',
  ), ...phrase('automate file management microsoft', 'automate file renaming onedrive', 'power automate rename files')],
    ad: rsa(
      headlines(
        '60 Seconds vs 60 Minutes',
        'AI Does It in One Step',
        'AI Renames OneDrive PDFs',
        'Beats Power Automate',
        'Free, no credit card',
        'Just Connect & Set Rules',
        'No Coding Required',
        'No Flows. No Connectors.',
        'OneDrive Integration',
        'Power Automate Too Complex?',
        'Try Free — 50 Documents',
        'Works with SharePoint Too',
      ),
      descriptions(
        'No coding, no connectors. Connect OneDrive, set rules. SharePoint too.',
        'Power Automate: 20 steps. renamed.to: zero. AI reads, names files.',
        'Stop building flows to rename files. Connect OneDrive, AI does it.',
        'Teams switched from Power Automate. 95% accuracy, zero maintenance.',
      ),
      url('https://www.renamed.to/integrations/onedrive'),
    ),
  })
  .group('sharepoint-naming-en', {
    keywords: [...broad(
    'microsoft 365 document management',
    'rename files in sharepoint',
    'sharepoint document management tool',
    'sharepoint document naming',
    'sharepoint document naming convention',
    'sharepoint document organization',
    'sharepoint file management',
    'sharepoint file management tool',
    'sharepoint file naming',
    'sharepoint folder organization',
  ), ...phrase(
    'rename files in sharepoint',
    'sharepoint document naming convention',
    'sharepoint document organization',
    'sharepoint file naming',
    'sharepoint naming convention tool',
    'sharepoint rename documents automatically',
  )],
    ad: rsa(
      headlines(
        '95% Accuracy. Try Free.',
        'Audit Trail Included',
        'Auto-Name Every PDF Uploaded',
        'Compliance Teams Love This',
        'Enforce File Standards — Auto',
        'Every Document Named Right',
        'Free, no credit card',
        'Naming Conventions by AI',
        'No IT Setup Required',
        'OneDrive Integration',
        'SharePoint Naming — AI Power',
        'Works with OneDrive Business',
      ),
      descriptions(
        'Enforce naming conventions across SharePoint. AI reads, renames PDFs.',
        'Every document named right, every time. Audit trail. Start free.',
        'SharePoint Online + OneDrive Business. Custom templates per library.',
        'Stop chasing colleagues about file names. AI applies your convention.',
      ),
      url('https://www.renamed.to/integrations/onedrive'),
    ),
  })
