// Imported from Google Ads on 2026-03-15
import { broad, daily, descriptions, exact, google, headlines, link, phrase, rsa, url } from '@upspawn/ads'

export default google.search('Search - PDF Renaming', {
  budget: daily(1.5),
  bidding: 'maximize-clicks',
  negatives: [...broad(
    'free',
    'linux',
    'convert',
    'guide',
    'tutorial',
    'freeware',
    'mac',
    'how to',
    'crack',
    'edit',
    'scanner',
    'free online',
    'sign',
    'fill',
    'adobe',
    'certificate',
    'open source',
    'split',
    'watermark',
    'what is',
    'terminal',
    'editor',
    'annotate',
    'divide',
    'combine',
    'bash',
    'command line',
    'separate',
    'merge',
    'compress',
    'rotate',
    'torrent',
    'redact',
    'bulk rename utility',
    'windows 11',
    'foxit',
    'demerge',
    'powershell',
    'tenorshare',
    'smallpdf',
    'advanced renamer',
    'note generator',
    'ilovepdf',
    'sejda',
    'pdnob',
    'hipdf',
  ), ...phrase(
    'document management system',
    'resize',
    'upscale',
    'conventions',
    'zusammenfassung',
    'combiner',
    'change file name',
    'summarize',
    'google word',
    'google doc',
    'pdf24',
    'pdffiller',
    'pdffiller com',
    'pdfelement',
    'pdf page remover',
    'how to rename a file',
    'pdf compressor',
    'printable list',
    'zusammenfassen',
    'windows file organizer',
    'how to rename photos',
    'google document',
    'google document editor',
    'google documents online',
    'how to rename',
    'file naming conventions',
    'compressed zip',
    'pdf candy',
    'lightpdf',
    'power automate',
    'powerautomate',
    'how to rename files',
    'how to rename folder',
    'upscale pdf',
    'bigpdf',
    'renamebest',
    'rename folder in windows',
    'rename a document in excel',
    'rename file on word',
    'rename photos on laptop',
    'upscale file pdf',
    'how to create file name',
    'upscale file',
    'google d o c s',
  )],
})
  .group('pdf-renamer-de', {
    keywords: [...exact('pdf automatisch umbenennen', 'pdf dateien automatisch umbenennen nach inhalt', 'pdf dateien umbenennen'), ...broad('pdf umbenennen')],
    ad: rsa(
      headlines(
        '50 kostenlose Umbenennungen',
        '95% Genauigkeit. Gratis Test',
        'In 60 Sekunden loslegen',
        'KI erkennt Daten & Betraege',
        'KI liest Inhalte & benennt um',
        'Keine Installation noetig',
        'Made in Germany. DSGVO-konform',
        'PDF Dateien umbenennen — KI',
        'PDF automatisch umbenennen',
        'Rechnungen, Vertraege, Belege',
      ),
      descriptions('95% Genauigkeit bei Rechnungen. 50 kostenlose Umbenennungen. Sofort los.', 'PDFs hochladen. KI erkennt Daten, Betraege, Firmen — benennt alles um.'),
      url('https://www.renamed.to/de/pdf-renamer'),
    ),
  })
  .group('pdf-renamer-en', {
    keywords: [...broad(
    'ai pdf renamer',
    'auto rename pdf',
    'auto rename pdf files based on content',
    'batch rename pdf files based on content',
    'pdf renamer',
    'rename a pdf',
    'rename pdf based on content',
  ), ...exact('auto rename pdf files', 'pdf file renamer')],
    ad: rsa(
      headlines(
        '50 Free Renames to Start',
        '95% Accuracy on Invoices',
        'AI Does It in 60 Seconds',
        'AI PDF Renamer — Try Free',
        'AI Reads Content & Names Files',
        'AI Reads Every Page',
        'Bookkeepers Save 10+ Hrs/Wk',
        'Dates, Amounts, Names — Done',
        'Invoices, Receipts, Contracts',
        'Made in Germany. GDPR Ready.',
        'No Software to Install',
        'Rename 1000 PDFs in Minutes',
        'Rename PDFs Based on Content',
        'Still Renaming PDFs by Hand?',
        'Works with Scanned Docs Too',
      ),
      descriptions(
        '95% accuracy on invoices & receipts. 50 free renames. No install needed.',
        'AI extracts key details, generates structured filenames. Custom templates.',
        'Stop opening each PDF to name it. Upload a batch, AI suggests names. Done.',
        'Upload PDFs. AI reads dates, amounts, names — renames every file. Preview first.',
      ),
      url('https://www.renamed.to/pdf-renamer'),
    ),
  })
  .sitelinks(
    link('See Pricing', 'https://www.renamed.to/pricing', { description1: '50 files free monthly', description2: 'Then $9 for 1,000 documents' }),
    link('Google Drive Integration', 'https://www.renamed.to/integrations/google-drive', { description1: 'Auto-rename in Google Drive', description2: 'Connect in one click' }),
    link('Dropbox Integration', 'https://www.renamed.to/integrations/dropbox', { description1: 'Auto-rename in Dropbox', description2: 'Connect in 3 minutes' }),
    link('Solutions for Accountants', 'https://www.renamed.to/solutions/accountants', { description1: 'Auto-name invoices and receipts', description2: 'By vendor, date, and amount' }),
  )
  .callouts('No Credit Card Required', 'AI-Powered', '95% Accuracy', '50 Free Documents')
